services:
  - type: web
    name: TolyattiFencingRegBot
    env: docker
    region: oregon
    plan: free        # или starter
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        fromPlan: true
      - key: PORT
        value: 10000
