services:
  - type: web
    name: TolyattiFencingRegBot
    plan: free
    region: oregon
    env: docker
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: WEBHOOK_URL
        fromPlan: true
      - key: DATABASE_URL
        fromDatabase:
          name: fencing-db
          property: connectionString

databases:
  - name: fencing-db
    plan: free
