services:
  - type: web
    name: TolyattiFencingRegBot
    plan: free
    region: oregon
    env: docker  # ← вот это важно!
    buildCommand: ""  # Dockerfile сам всё сделает
    startCommand: ""  # не нужно, если есть CMD в Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        fromPlan: true
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: fencing-db
          property: connectionString

databases:
  - name: fencing-db
    plan: free
